### ISSUE TITLE
Attach is deprecated

### ISSUE THREAD

**Issue by hjbaard** [skhamis/Unity-ECS-RTS#4]
I was following your tutorial but Attach isn't present anymore.

**Comment by ghost** [comment]
I have same issue.
Unity 2019.02 version I want 2019 version convert source please help me@@

**Comment by skhamis** [comment]
Thanks for making an issue! I have since updated the project and use the "recommended" way to have hierarchical components. Will get a video shortly in the next coming days. Closing out!
